name: float_elf
description: simple scheme for draggable floating ball in app
version: 0.0.4
author: jkouulong <jkouulong@gmail.com>
homepage: https://github.com/jkouubb/float_elf

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
